In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
cd /content/drive/MyDrive/PPW/tugas

/content/drive/MyDrive/PPW/tugas


In [10]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

import numpy as np
from sklearn.decomposition import TruncatedSVD
from scipy.linalg import svd

In [22]:
df = pd.read_csv("/content/drive/My Drive/PPW/tugas/preprosesing-berita.csv")

In [29]:
import re

# Fungsi membersihkan angka
def remove_numbers(text):
    return re.sub(r'\b\d+\b', '', text)

# Terapkan fungsi pada kolom teks yang diproses
df['stemming'] = df['stemming'].apply(remove_numbers)

In [30]:
x = df['stemming'].values
y = df['Kategori'].values

Xtrain, Xtest,Ytrain,Ytest = train_test_split(x,y,test_size=0.2,random_state=2)

In [32]:
vect = TfidfVectorizer()
X = vect.fit_transform(Xtrain)

X_array = vect.transform(Xtrain)

X_array.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.0855273 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.0855273 ],
       [0.        , 0.0309078 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.02381859, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [33]:
X_array.shape

(80, 1546)

In [14]:
# Misalkan ini adalah hasil dari TF-IDF
X_array = vect.transform(Xtrain).toarray()

# Menggunakan SVD dari SciPy
U, sigma, Vt = svd(X_array, full_matrices=False)

print("Matriks U:")
print(U)

print("\nMatriks Sigma (diagonal):")
print(sigma)

print("\nMatriks V^T:")
print(Vt)

Matriks U:
[[-0.1145705  -0.01620273 -0.01742587 ... -0.20942476  0.26326105
  -0.30205781]
 [-0.1145705  -0.01620273 -0.01742587 ...  0.11805281 -0.21240252
   0.12618596]
 [-0.02970658  0.03671417  0.01184012 ... -0.00409269 -0.09326571
   0.15185628]
 ...
 [-0.06768585  0.09809556 -0.05607829 ...  0.18288395  0.1210307
  -0.0353708 ]
 [-0.10741115 -0.02430151  0.00056776 ... -0.10604646  0.25524068
   0.06743087]
 [-0.05068004  0.01092239  0.00597605 ...  0.08377814  0.23423134
   0.36503413]]

Matriks Sigma (diagonal):
[2.98919634e+00 2.70814692e+00 2.63613190e+00 2.48242145e+00
 2.43719403e+00 2.31240642e+00 2.27587438e+00 2.23826734e+00
 2.19057412e+00 2.17206082e+00 2.06670969e+00 2.01165908e+00
 1.94446734e+00 1.89002663e+00 1.71350129e+00 1.00930162e+00
 1.08231717e-15 7.82276593e-16 7.02730166e-16 6.37494959e-16
 5.92725243e-16 5.19215902e-16 4.57290159e-16 3.50644871e-16
 2.68389578e-16 2.68389578e-16 2.68389578e-16 2.68389578e-16
 2.68389578e-16 2.68389578e-16 2.68389578e-1

In [19]:
print(U.shape)
print(sigma.shape)
print(Vt.shape)

(80, 80)
(80,)
(80, 1584)


In [20]:
# Jika ingin melakukan SVD terbatas untuk pengurangan dimensi, Anda bisa menggunakan TruncatedSVD seperti berikut:

from sklearn.decomposition import TruncatedSVD

# Menggunakan Truncated SVD
svd = TruncatedSVD(n_components=100)  # Ubah jumlah komponen sesuai kebutuhan
X_svd = svd.fit_transform(X_array)

print("Matriks U yang tereduksi:")
print(X_svd)

print("\nMatriks Sigma:")
print(svd.singular_values_)

print("\nMatriks V^T yang tereduksi:")
print(svd.components_)

Matriks U yang tereduksi:
[[ 3.42473707e-01 -4.38793837e-02  4.59368918e-02 ... -6.07153217e-18
  -3.46944695e-18 -3.12250226e-17]
 [ 3.42473707e-01 -4.38793837e-02  4.59368918e-02 ... -6.07153217e-18
  -3.46944695e-18 -3.12250226e-17]
 [ 8.87988071e-02  9.94273760e-02 -3.12121088e-02 ... -8.67361738e-19
   7.37257477e-18  3.46944695e-17]
 ...
 [ 2.02326284e-01  2.65657192e-01  1.47829759e-01 ... -2.03830008e-17
   2.41234983e-18  3.85975973e-17]
 [ 3.21073022e-01 -6.58120517e-02 -1.49669559e-03 ...  5.63785130e-18
   7.80625564e-18 -5.24753851e-17]
 [ 1.51492600e-01  2.95794331e-02 -1.57536624e-02 ...  3.38271078e-17
   2.34187669e-17 -3.35018471e-17]]

Matriks Sigma:
[2.98919634e+00 2.70814692e+00 2.63613190e+00 2.48242145e+00
 2.43719403e+00 2.31240642e+00 2.27587438e+00 2.23826734e+00
 2.19057412e+00 2.17206082e+00 2.06670969e+00 2.01165908e+00
 1.94446734e+00 1.89002663e+00 1.71350129e+00 1.00930162e+00
 2.64576558e-16 2.64576558e-16 2.64576558e-16 2.64576558e-16
 2.64576558e-16 2

In [ ]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

# Asumsikan data Xtrain sudah ada dari sebelumnya
# Misalnya Xtrain adalah corpus yang sudah di-preprocessing

vect = TfidfVectorizer()
X = vect.fit_transform(Xtrain)  # Menghasilkan TF-IDF
X_array = X.toarray()  # Mengubah sparse matrix ke numpy array

# Menggunakan numpy.linalg.svd pada data TF-IDF
U, sigma, Vt = np.linalg.svd(X_array, full_matrices=False)

# Menampilkan hasil SVD
print("Matriks U:")
print(U)

print("\nNilai Sigma (diagonal):")
print(sigma)

print("\nMatriks V^T:")
print(Vt)


Matriks U:
[[-0.1145705  -0.01620273 -0.01742587 ... -0.01706466 -0.22695109
   0.04966712]
 [-0.1145705  -0.01620273 -0.01742587 ... -0.09723356  0.11493548
   0.09390375]
 [-0.02970658  0.03671417  0.01184012 ... -0.14000571 -0.27983903
   0.08810739]
 ...
 [-0.06768585  0.09809556 -0.05607829 ... -0.0155243  -0.01761336
  -0.03452286]
 [-0.10741115 -0.02430151  0.00056776 ... -0.03139416  0.01893124
   0.009521  ]
 [-0.05068004  0.01092239  0.00597605 ...  0.0024299   0.01458759
   0.00603096]]

Nilai Sigma (diagonal):
[2.98919634e+00 2.70814692e+00 2.63613190e+00 2.48242145e+00
 2.43719403e+00 2.31240642e+00 2.27587438e+00 2.23826734e+00
 2.19057412e+00 2.17206082e+00 2.06670969e+00 2.01165908e+00
 1.94446734e+00 1.89002663e+00 1.71350129e+00 1.00930162e+00
 2.96328178e-15 1.78847271e-15 1.23464272e-15 8.19478335e-16
 6.98755990e-16 6.77252866e-16 6.35327890e-16 5.21446719e-16
 4.45633642e-16 3.35457349e-16 2.68389578e-16 2.68389578e-16
 2.68389578e-16 2.68389578e-16 2.68389578e-16

coba-coba:

[ini ya](https://machinelearningmastery.com/singular-value-decomposition-for-machine-learning/)


In [ ]:
# Reconstruct SVD
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd

# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)

# Singular-value decomposition
U, s, VT = svd(A)

# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))

# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)

# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [ ]:
from numpy import array, diag, dot, zeros
from scipy.linalg import svd

# Mendefinisikan matriks asli A
A = array([[1, 2], [3, 4], [5, 6]])
print("Matriks asli A:")
print(A)

# Melakukan dekomposisi SVD pada matriks A
U, s, VT = svd(A)

# Membuat matriks Sigma dengan ukuran yang sama dengan A, diisi dengan nol
Sigma = zeros((A.shape[0], A.shape[1]))

# Mengisi Sigma dengan hanya satu nilai singular terbesar (yaitu, mengurangi fitur)
Sigma[0, 0] = s[0]  # Menyimpan hanya nilai singular terbesar

# Merekonstruksi matriks yang telah direduksi fiturnya
B_reduced = U.dot(Sigma.dot(VT))
print("\nMatriks hasil rekonstruksi dengan fitur yang direduksi:")
print(B_reduced)

Matriks asli A:
[[1 2]
 [3 4]
 [5 6]]

Matriks hasil rekonstruksi dengan fitur yang direduksi:
[[1.35662819 1.71846235]
 [3.09719707 3.92326845]
 [4.83776596 6.12807454]]


coba lagi

In [5]:
import numpy as np
from sklearn.decomposition import TruncatedSVD

# Contoh matriks sederhana
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Menghitung SVD secara manual
U, sigma, Vt = np.linalg.svd(A)

# Menampilkan hasil SVD
print("Matriks U:\n", U)
print("\nMatriks Sigma:\n", np.diag(sigma))
print("\nMatriks V^t:\n", Vt)

# Mereduksi matriks A menggunakan TruncatedSVD
# Pilih jumlah komponen yang ingin dipertahankan, misalnya 2
svd = TruncatedSVD(n_components=2)
A_reduced = svd.fit_transform(A)

# Menampilkan matriks tereduksi
print("\nMatriks A setelah reduksi:\n", A_reduced)

Matriks U:
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]

Matriks Sigma:
 [[1.68481034e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.06836951e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.41842475e-16]]

Matriks V^t:
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]

Matriks A setelah reduksi:
 [[ 3.6196     -0.94789022]
 [ 8.77091014 -0.26671199]
 [13.92222029  0.41446624]]
